### ISSUE TITLE
sekiro java sdk连接server可以使用代理吗？

### ISSUE THREAD

**Issue by WuJianeng** [yint-tech/sekiro-samples#3]
在使用 SekiroInvoker 方式连接 server 时遇到下面的错误：
```
[2023-12-19T15:09:03.036]2023-12-19 15:09:03,035 [nioEventLoopGroup-2-7] [1;31m[0;39mERROR [36m[0;39mSekiro.print      - [xxx.xxx.xxx.xxx:5602]connect to sekiro server failed
[2023-12-19T15:09:03.036]cn.iinti.sekiro3.business.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: /xxx.xxx.xxx.xxx:5602
[2023-12-19T15:09:03.036]	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2023-12-19T15:09:03.036]	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
[2023-12-19T15:09:03.036]	at cn.iinti.sekiro3.business.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:258)
[2023-12-19T15:09:03.036]	at cn.iinti.sekiro3.business.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
[2023-12-19T15:09:03.037]	at cn.iinti.sekiro3.business.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:631)
[2023-12-19T15:09:03.037]	at cn.iinti.sekiro3.business.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
[2023-12-19T15:09:03.037]	at cn.iinti.sekiro3.business.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
[2023-12-19T15:09:03.037]	at cn.iinti.sekiro3.business.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
[2023-12-19T15:09:03.037]	at cn.iinti.sekiro3.business.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
[2023-12-19T15:09:03.037]	at cn.iinti.sekiro3.business.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
```
看起来是 sekiro sdk 在使用 netty 尝试连接 server 时遇到的错误。由于部署环境限制，不能直连 server，需要走代理，请问现在 sdk 支持通过代理连接 server 吗？

**Comment by liguobao** [comment]
这个可能不太行，因为这里走的协议栈可能没办法兼容。

**Comment by WuJianeng** [comment]
好的，我再了解一下netty

**Comment by iinti** [comment]
sekiro sdk底层没有支持代理。如果咱们需要的话，可能得有很大的定制化成本了，暂时建议还是通过其他运维层面手段来绕过这个问题

**Comment by WuJianeng** [comment]
谢谢，目前还是使用http方式调用，没有用SekiroInvoker来发请求
